name: Daily Job Scraper

on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r scraper/requirements.txt
          python -m playwright install
          python -m playwright install-deps

      - name: Run scraper
        run: |
          cd scraper
          python main.py

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update job listings and mind map"
          file_pattern: |
            data/jobs.json
            data/mindmap.json

